kind: Service
apiVersion: v1
metadata:
  name: art-svc
  labels:
    app: art
spec:
  type: NodePort
  selector:
    app: art
  ports:
  - port: 8080
    targetPort: 8080
    name: http
---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: art-deploy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: art
  template:
    metadata:
      labels:
        app: art
        version: v1
    spec:
      containers:
      - name: art-server
        image: art-server
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8080
---
